name: Push to ECR deployment ENV

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-deploy-develop:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 581741715630.dkr.ecr.ap-south-1.amazonaws.com
        env:
          AWS_REGION: ap-south-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Generate timestamp for versioning
        id: timestamp
        run: |
          UNIX_TIME=$(date +%s)
          echo "::set-output name=UNIX_TIMESTAMP::$UNIX_TIME"

      - name: Build and push Docker image
        run: |
          VERSION="${{ steps.timestamp.outputs.UNIX_TIMESTAMP }}"
          docker build -t go-api-template .
          docker tag go-api-template:latest 581741715630.dkr.ecr.ap-south-1.amazonaws.com/go-api-template:$VERSION
          docker push 581741715630.dkr.ecr.ap-south-1.amazonaws.com/go-api-template:$VERSION
        env:
          AWS_REGION: ap-south-1
          name: Push to ECR and Update ECS

      - name: Update ECS Task Definition
        run: |
          aws ecs register-task-definition --cli-input-json '{
            "family": "develop",
            "containerDefinitions": [
              {
                "name": "develop-container",
                "image": "581741715630.dkr.ecr.ap-south-1.amazonaws.com/go-api-template:$VERSION",
                "memory": 512,
                "cpu": 256
              }
            ]
          }'
        env:
          AWS_REGION: ap-south-1

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster go-dev --service develop --force-new-deployment --desired-count 1
        env:
          AWS_REGION: ap-south-1

  build-deploy-staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 581741715630.dkr.ecr.ap-south-1.amazonaws.com
        env:
          AWS_REGION: ap-south-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Generate timestamp for versioning
        id: timestamp
        run: |
          UNIX_TIME=$(date +%s)
          echo "::set-output name=UNIX_TIMESTAMP::$UNIX_TIME"

      - name: Build and push Docker image
        run: |
          VERSION="${{ steps.timestamp.outputs.UNIX_TIMESTAMP }}"
          docker build -t go-api-template .
          docker tag go-api-template:latest 581741715630.dkr.ecr.ap-south-1.amazonaws.com/go-api-template:$VERSION
          docker push 581741715630.dkr.ecr.ap-south-1.amazonaws.com/go-api-template:$VERSION
        env:
          AWS_REGION: ap-south-1
          name: Push to ECR and Update ECS

      - name: Update ECS Task Definition
        run: |
          aws ecs register-task-definition --cli-input-json '{
            "family": "stage",
            "containerDefinitions": [
              {
                "name": "stage-deployment",
                "image": "581741715630.dkr.ecr.ap-south-1.amazonaws.com/go-api-template:$VERSION",
                "memory": 512,
                "cpu": 256
              }
            ]
          }'
        env:
          AWS_REGION: ap-south-1

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster go-stage --service stage --force-new-deployment --desired-count 1
        env:
          AWS_REGION: ap-south-1
