name: Production Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'prod'

jobs:
  build-deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 581741715630.dkr.ecr.ap-south-1.amazonaws.com
        env:
          AWS_REGION: ap-south-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image
        run: |
          docker build -t go-api-template .
          docker tag go-api-template:latest 581741715630.dkr.ecr.ap-south-1.amazonaws.com/go-api-template:latest
          docker push 581741715630.dkr.ecr.ap-south-1.amazonaws.com/go-api-template:latest
        env:
          AWS_REGION: ap-south-1
          name: Push to ECR and Update ECS

      - name: Update ECS Task Definition
        run: |
          aws ecs register-task-definition --cli-input-json '{
            "family": "go-production-deployment",
            "containerDefinitions": [
              {
                "name": "go-production-deployment",
                "image": "581741715630.dkr.ecr.ap-south-1.amazonaws.com/go-api-template:latest",
                "memory": 512,
                "cpu": 256
              }
            ]
          }'
        env:
          AWS_REGION: ap-south-1

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster go-production-deployment --service production --force-new-deployment --desired-count 1
        env:
          AWS_REGION: ap-south-1